steps:
  - name: 'openjdk:17'
    entrypoint: 'java'
    args: ['-version']
  #- name: 'gcr.io/cloud-builders/gradle'
  #  args: ['clean', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/santhosh202310/spring-boot-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/santhosh202310/spring-boot-app']
  - name: 'gcr.io/googgle.com/cloudsdktool/cloud-sdk'
    args: ['run','deploy','spring-boot-cicd','--image',gcr.io/santhosh202310/spring-boot-app
          ,'--region','us-central1','--allow-unauthenticated']
images:
  - gcr.io/santhosh202310/spring-boot-app
 
