  steps:
  # Step 1 Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/santhosh202310/spring-boot-app-image:latest', '.']
  # Step 2 Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/santhosh202310/spring-boot-app-image:latest']
  # Step 3 Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'spring-boot-app-image'
    - '--image'
    - 'gcr.io/santhosh202310/spring-boot-app-image:latest'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'

  # Step 4 Pull the Image from GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull Image from GCR'
    args: ['pull', 'gcr.io/santhosh202310/spring-boot-app-image:latest']
  
  # Configure JFrog CLI to point to Jfrog Artifactory 
  - name: 'jfrog-docker-reg2.bintray.io/google-cloud-builder/java/jfrog:0.1'
    entrypoint: 'bash'
    args: ['-c', 'jfrog rt c rt-mvn-repo --url=https://chsanthoshsep.jfrog.io --user=chsanthosh.sep@gmail.com --password=$$JFROG_ARTIFACTORY_API_KEY']
    secretEnv: ['JFROG_ARTIFACTORY_API_KEY']
    dir: 'maven-example'
   
  # Step 5 Log in to JFrog Artifactory
  - name: 'gcr.io/cloud-builders/docker'
    id: 'fetch-secret'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
     echo "Fetching secrets..."
     USERNAME='chsanthosh.sep@gmail.com'
     # Temporarily print the length of the API key for debugging
     echo "Username: $$USERNAME"
     echo " API Key: $$JFROG_ARTIFACTORY_API_KEY"
     echo $$JFROG_ARTIFACTORY_API_KEY | docker login -u $$USERNAME --password-stdin https://chsanthoshsep.jfrog.io/
    secretEnv:
    - 'JFROG_ARTIFACTORY_API_KEY'
  
  # Step 6 Retag Image for JFrog
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Retag Image for JFrog'
    args: ['tag', 'gcr.io/santhosh202310/${PROJECT_DOCKER_REPO_PATH}:latest', 'chsanthoshsep.jfrog.io/${PROJECT_DOCKER_REPO_PATH}/${SRE_PC_SERVICENAME}:latest']
  
  # Step 7 Push the image to JFrog Artifactory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'chsanthoshsep.jfrog.io/spring-boot-app-docker/spring-boot-app-image:latest']
  
  # available secrets
  availableSecrets:
   secretManager:
    - versionName: projects/201747314915/secrets/jfrog-artifactory-api-key/versions/latest
      env: 'JFROG_ARTIFACTORY_API_KEY'

  images:
  - 'gcr.io/santhosh202310/spring-boot-app-image:latest'

  options:
    env:
      - "SRE_PC_SERVICENAME=spring-boot-app-image"
      - "PROJECT_DOCKER_REPO_PATH=spring-boot-app-docker"

