steps:
  
  - name: 'openjdk:17'
    entrypoint: 'java'
    args: ['-version']
  
  #- name: 'gcr.io/cloud-builders/gradle'
  #  args: ['clean', 'build']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/santhosh202310/spring-boot-app:latest', '.']
 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/santhosh202310/spring-boot-app:latest']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'service'
      - '--region=us-central1'
      - '--image=gcr.io/santhosh202310/spring-boot-app:latest'
      - '--platform=managed'
      - '--allow-authenticated'
substitutions:
  _VERBOSITY: '1'

 
