steps:
  
  - name: 'openjdk:17'
    entrypoint: 'java'
    args: ['-version']
  
  #- name: 'gcr.io/cloud-builders/gradle'
  #  args: ['clean', 'build']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/santhosh202310/spring-boot-app:$SHORT_SHA', '.']
 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/santhosh202310/spring-boot-app:$SHORT_SHA']
  
  - name: 'gcr.io/google.com/cloud-builders/gcloud'
    args: ['run', 'deploy', 'santhosh202310', '--region=us-central1', '--platform=managed', '--image=gcr.io/santhosh202310/spring-boot-app:latest']
 
