steps:
  - name: 'openjdk:17'
    entrypoint: 'java'
    args: ['-version']
  #- name: 'gcr.io/cloud-builders/gradle'
  #  args: ['clean', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/santhosh202310/spring-boot-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/santhosh202310/spring-boot-app']
  - name: 'gcr.io/santhosh202310/spring-boot-app:v1.0'
    args: ["service", "--action", "deploy"]
substitutions:
  _VERBOSITY: '1'
 
