steps:
  
  - name: 'openjdk:17'
    entrypoint: 'java'
    args: ['-version']
  #- name: 'gcr.io/cloud-builders/gradle'
  #  args: ['clean', 'build']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ["init"]  
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/santhosh202310/spring-boot-app:latest', '.']
 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/santhosh202310/spring-boot-app:latest']
  
  - name: 'gcr.io/santhosh202310/spring-boot-app:latest'
    args: ["service", "--action", "deploy"]
substitutions:
  _VERBOSITY: '1'

 
